from __future__ import annotations

import html
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.api.schemas import SiteAnalysisResponse, SiteHeatmapResponse

DISCLAIMER = (
    "This report is generated by CHITTA as a preliminary screening tool only. "
    "It is not a bankable wind resource assessment, feasibility study, or "
    "engineering recommendation. Results should be validated with on-site "
    "measurement, detailed GIS analysis, permitting review, and professional "
    "due diligence before any investment or development decision."
)

ACCENT = colors.HexColor("#047857")
MUTED = colors.HexColor("#64748b")
LIGHT_BG = colors.HexColor("#f0fdf4")


def _esc(text: str) -> str:
    return html.escape(str(text))


def _bullet_list(items: list[str], style: ParagraphStyle) -> list[Any]:
    flow: list[Any] = []
    for item in items:
        flow.append(Paragraph(f"• {_esc(item)}", style))
        flow.append(Spacer(1, 4))
    return flow


def _section_heading(title: str, styles: dict[str, ParagraphStyle]) -> list[Any]:
    return [
        Spacer(1, 10),
        Paragraph(_esc(title), styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")),
        Spacer(1, 8),
    ]


def _score_table(data: list[list[str]]) -> Table:
    table = Table(data, colWidths=[2.4 * inch, 1.2 * inch, 2.9 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (1, 0), (1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def _wind_findings(analysis: SiteAnalysisResponse) -> list[str]:
    m = analysis.metrics
    findings = [f"Wind suitability score: {m.windScore:.0f}/100."]
    debug = analysis.debug or {}
    sources = debug.get("sources") if isinstance(debug.get("sources"), dict) else None
    wind_src = sources.get("wind") if isinstance(sources, dict) else None
    if isinstance(wind_src, dict):
        raw = wind_src.get("raw") if isinstance(wind_src.get("raw"), dict) else {}
        if raw.get("mean_speed_mps") is not None:
            findings.append(f"Mean wind speed (source data): {float(raw['mean_speed_mps']):.2f} m/s.")
        findings.append(f"Wind data provider: {wind_src.get('provider', 'unknown')}.")
    for item in analysis.report.siteStrengths + analysis.report.risks:
        if "wind" in item.lower():
            findings.append(item)
    return findings


def _terrain_findings(analysis: SiteAnalysisResponse) -> list[str]:
    m = analysis.metrics
    findings = [
        f"Terrain suitability score: {m.terrainScore:.0f}/100.",
        f"Site elevation: {m.elevationM:.0f} m.",
        f"Terrain complexity index: {m.terrainComplexity:.2f}.",
    ]
    debug = analysis.debug or {}
    sources = debug.get("sources") if isinstance(debug.get("sources"), dict) else None
    elev_src = sources.get("elevation") if isinstance(sources, dict) else None
    if isinstance(elev_src, dict):
        findings.append(f"Elevation data provider: {elev_src.get('provider', 'unknown')}.")
    for item in analysis.report.siteStrengths + analysis.report.risks:
        lower = item.lower()
        if any(k in lower for k in ("terrain", "buildable", "slope", "elevation")):
            findings.append(item)
    return findings


def generate_site_report_pdf(
    analysis: SiteAnalysisResponse,
    heatmap: SiteHeatmapResponse | None = None,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title="CHITTA Site Assessment Report",
    )

    base = getSampleStyleSheet()
    styles = {
        "Title": ParagraphStyle(
            "Title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=ACCENT,
            spaceAfter=6,
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=MUTED,
            spaceAfter=4,
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=4,
        ),
        "Body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
        ),
        "Disclaimer": ParagraphStyle(
            "Disclaimer",
            parent=base["Normal"],
            fontSize=8,
            leading=11,
            textColor=MUTED,
            backColor=colors.HexColor("#f8fafc"),
            borderPadding=8,
        ),
    }

    lat = analysis.inputs.latitude
    lng = analysis.inputs.longitude
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    m = analysis.metrics

    story: list[Any] = [
        Paragraph("CHITTA Site Assessment Report", styles["Title"]),
        Paragraph(
            "Climate Heuristics &amp; Intelligent Turbine Terrain Analysis",
            styles["Subtitle"],
        ),
        Spacer(1, 6),
        Paragraph(f"<b>Coordinates:</b> {lat:.5f}, {lng:.5f}", styles["Body"]),
        Paragraph(f"<b>Generated:</b> {_esc(ts)}", styles["Body"]),
        Spacer(1, 12),
        Paragraph(
            f"<b>Total suitability:</b> {analysis.totalSuitabilityScore:.0f}/100",
            styles["Body"],
        ),
        Spacer(1, 16),
    ]

    story += _section_heading("Executive Summary", styles)
    story.append(Paragraph(_esc(analysis.report.executiveSummary), styles["Body"]))
    story.append(Spacer(1, 8))

    story += _section_heading("Score Summary", styles)
    score_rows = [
        ["Metric", "Score", "Notes"],
        ["Wind", f"{m.windScore:.0f}", "Regional wind potential"],
        ["Terrain", f"{m.terrainScore:.0f}", "Buildability & roughness"],
        ["Accessibility", f"{m.accessibilityScore:.0f}", "Road/grid proxy"],
        ["Confidence", f"{m.confidenceScore:.0f}", "Data completeness"],
        ["Total suitability", f"{analysis.totalSuitabilityScore:.0f}", "Weighted composite"],
    ]
    story.append(_score_table(score_rows))
    story.append(Spacer(1, 8))

    if heatmap and heatmap.bestCells:
        story += _section_heading("Top 3 Candidate Zones", styles)
        zone_rows = [["Rank", "Label", "Total", "Wind", "Terrain", "Coords"]]
        for idx, cell in enumerate(heatmap.bestCells[:3], start=1):
            cm = cell.metrics
            zone_rows.append(
                [
                    str(idx),
                    cell.label,
                    f"{cm.totalSuitability:.0f}",
                    f"{cm.windScore:.0f}",
                    f"{cm.terrainScore:.0f}",
                    f"{cell.latitude:.4f}, {cell.longitude:.4f}",
                ]
            )
        zone_table = Table(
            zone_rows,
            colWidths=[0.45 * inch, 1.5 * inch, 0.65 * inch, 0.65 * inch, 0.75 * inch, 1.5 * inch],
        )
        zone_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(zone_table)
        story.append(
            Paragraph(
                f"Heatmap coverage: {heatmap.radiusKm:.0f} km radius, {heatmap.gridSize}×{heatmap.gridSize} grid.",
                styles["Subtitle"],
            )
        )

    story += _section_heading("Wind Findings", styles)
    story += _bullet_list(_wind_findings(analysis), styles["Body"])

    story += _section_heading("Terrain Findings", styles)
    story += _bullet_list(_terrain_findings(analysis), styles["Body"])

    story += _section_heading("Risks and Limitations", styles)
    limitations = list(analysis.report.risks) + list(analysis.report.confidenceNotes)
    story += _bullet_list(limitations, styles["Body"])

    story += _section_heading("Recommendations", styles)
    story += _bullet_list(analysis.report.recommendations, styles["Body"])

    story += _section_heading("Data Sources", styles)
    story += _bullet_list(analysis.report.dataSources, styles["Body"])

    story += _section_heading("Disclaimer", styles)
    story.append(Paragraph(_esc(DISCLAIMER), styles["Disclaimer"]))

    doc.build(story)
    return buffer.getvalue()
