from __future__ import annotations

import html
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.api.schemas import MethodologyMetadata, SiteAnalysisResponse, SiteHeatmapResponse
from app.services.methodology import TOTAL_SUITABILITY_FORMULA_PLAIN, WIND_SCORE_FORMULA_PLAIN

DISCLAIMER = (
    "This report is generated by CHITTA as a preliminary screening tool only. "
    "It is not a bankable wind resource assessment, feasibility study, or "
    "engineering recommendation. Results should be validated with on-site "
    "measurement, detailed GIS analysis, permitting review, and professional "
    "due diligence before any investment or development decision."
)

ACCENT = colors.HexColor("#047857")
MUTED = colors.HexColor("#64748b")
LIGHT_BG = colors.HexColor("#f0fdf4")


def _esc(text: str) -> str:
    return html.escape(str(text))


def _fmt_score(v: float | None) -> str:
    return "Unavailable" if v is None else f"{v:.0f}"


def _bullet_list(items: list[str], style: ParagraphStyle) -> list[Any]:
    flow: list[Any] = []
    for item in items:
        flow.append(Paragraph(f"• {_esc(item)}", style))
        flow.append(Spacer(1, 4))
    return flow


def _section_heading(title: str, styles: dict[str, ParagraphStyle]) -> list[Any]:
    return [
        Spacer(1, 10),
        Paragraph(_esc(title), styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")),
        Spacer(1, 8),
    ]


def _score_table(data: list[list[str]]) -> Table:
    table = Table(data, colWidths=[2.4 * inch, 1.2 * inch, 2.9 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (1, 0), (1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def _wind_findings(analysis: SiteAnalysisResponse) -> list[str]:
    m = analysis.metrics
    findings = [f"Wind suitability score: {_fmt_score(m.windScore)}/100."]
    if m.windSpeedAtHub is not None:
        findings.append(f"Mean wind speed at hub height: {m.windSpeedAtHub:.2f} m/s.")
    debug = analysis.debug or {}
    sources = debug.get("sources") if isinstance(debug.get("sources"), dict) else None
    wind_src = sources.get("wind") if isinstance(sources, dict) else None
    if isinstance(wind_src, dict):
        raw = wind_src.get("raw") if isinstance(wind_src.get("raw"), dict) else {}
        hub_h = raw.get("hub_height_m")
        if hub_h is not None:
            findings.append(f"Data height: {hub_h} m (highest available from NASA POWER).")
        findings.append(f"Wind data provider: {wind_src.get('provider', 'unknown')}.")
    for item in analysis.report.siteStrengths + analysis.report.risks:
        if "wind" in item.lower():
            findings.append(item)
    return findings


def _terrain_findings(analysis: SiteAnalysisResponse) -> list[str]:
    m = analysis.metrics
    findings = [
        f"Terrain suitability score: {_fmt_score(m.terrainScore)}/100.",
        f"Site elevation: {_fmt_score(m.elevationM)} m." if m.elevationM is not None else "Site elevation: Unavailable.",
        f"Terrain complexity index: {m.terrainComplexity:.2f}." if m.terrainComplexity is not None else "Terrain complexity index: Unavailable.",
    ]
    debug = analysis.debug or {}
    sources = debug.get("sources") if isinstance(debug.get("sources"), dict) else None
    elev_src = sources.get("elevation") if isinstance(sources, dict) else None
    if isinstance(elev_src, dict):
        findings.append(f"Elevation data provider: {elev_src.get('provider', 'unknown')}.")
    for item in analysis.report.siteStrengths + analysis.report.risks:
        lower = item.lower()
        if any(k in lower for k in ("terrain", "buildable", "slope", "elevation")):
            findings.append(item)
    return findings


_LEVEL_LABELS = {"high": "HIGH RISK", "medium": "MEDIUM RISK", "low": "LOW RISK", "unknown": "UNKNOWN"}
_SEVERITY_LABELS = {"critical": "CRITICAL", "warning": "WARNING"}


def _development_risk_section(analysis: SiteAnalysisResponse, styles: dict) -> list[Any]:
    do = analysis.developmentOutlook
    if do is None:
        return []

    flow: list[Any] = []
    flow += _section_heading("Development Risk Assessment", styles)

    outlook_label = do.developmentOutlook.upper().replace("_", " ")
    flow.append(
        Paragraph(
            f"<b>Development Outlook: {_esc(outlook_label)}</b>",
            ParagraphStyle(
                "OutlookLabel",
                parent=styles["Body"],
                fontSize=11,
                textColor=ACCENT,
                spaceAfter=6,
            ),
        )
    )
    flow.append(Paragraph(_esc(do.narrativeSummary), styles["Body"]))
    flow.append(Spacer(1, 6))

    fitness = do.fitnessTest
    flow.append(
        Paragraph(
            f"<b>Project fitness:</b> {fitness.testsPassed}/{fitness.totalTests} tests passed — Risk band: {_esc(fitness.riskBand.upper().replace('_', ' '))}",
            styles["Body"],
        )
    )
    flow.append(Spacer(1, 6))

    # Fatal flaws
    if do.fatalFlaws:
        flow.append(Paragraph("<b>Potential Fatal Flaws</b>", styles["Body"]))
        flow.append(Spacer(1, 4))
        ff_rows = [["Severity", "Category", "Description", "Next Step"]]
        for ff in do.fatalFlaws:
            ff_rows.append([
                _SEVERITY_LABELS.get(ff.severity, ff.severity.upper()),
                _esc(ff.category),
                _esc(ff.description[:120] + "…" if len(ff.description) > 120 else ff.description),
                _esc(ff.nextStep[:80] + "…" if len(ff.nextStep) > 80 else ff.nextStep),
            ])
        ff_table = Table(ff_rows, colWidths=[0.8 * inch, 1.2 * inch, 2.6 * inch, 1.9 * inch])
        ff_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#9f1239")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff1f2")]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        flow.append(ff_table)
        flow.append(Spacer(1, 8))

    # Risk register
    flow.append(Paragraph("<b>Risk Register</b>", styles["Body"]))
    flow.append(Spacer(1, 4))
    rr_rows = [["Category", "Level", "Knowledge", "Summary"]]
    for item in do.riskRegister.categories:
        rr_rows.append([
            _esc(item.category),
            _LEVEL_LABELS.get(item.level, item.level.upper()),
            _esc(item.knowledgeClass.replace("_", " ")),
            _esc(item.summary[:100] + "…" if len(item.summary) > 100 else item.summary),
        ])
    rr_table = Table(rr_rows, colWidths=[1.4 * inch, 0.85 * inch, 1.1 * inch, 3.15 * inch])
    rr_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    flow.append(rr_table)
    flow.append(Spacer(1, 8))

    # Fitness test summary
    flow.append(Paragraph("<b>Project Fitness Test Results</b>", styles["Body"]))
    flow.append(Spacer(1, 4))
    ft_rows = [["Test", "Result", "Impact"]]
    for test in fitness.tests:
        ft_rows.append([
            _esc(test.testName),
            "PASS" if test.passed else "FAIL",
            _esc(test.impactSummary[:80] + "…" if len(test.impactSummary) > 80 else test.impactSummary),
        ])
    ft_table = Table(ft_rows, colWidths=[2.5 * inch, 0.6 * inch, 3.4 * inch])
    ft_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    flow.append(ft_table)
    flow.append(Spacer(1, 8))

    # Next investigation priorities
    if do.nextInvestigationPriorities:
        flow.append(Paragraph("<b>Next Investigation Priorities</b>", styles["Body"]))
        for i, priority in enumerate(do.nextInvestigationPriorities, 1):
            flow.append(Paragraph(f"{i}. {_esc(priority)}", styles["Body"]))
            flow.append(Spacer(1, 3))
        flow.append(Spacer(1, 4))

    return flow


def generate_site_report_pdf(
    analysis: SiteAnalysisResponse,
    heatmap: SiteHeatmapResponse | None = None,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title="CHITTA Site Assessment Report",
    )

    base = getSampleStyleSheet()
    styles = {
        "Title": ParagraphStyle(
            "Title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=ACCENT,
            spaceAfter=6,
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=MUTED,
            spaceAfter=4,
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=4,
        ),
        "Body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
        ),
        "Disclaimer": ParagraphStyle(
            "Disclaimer",
            parent=base["Normal"],
            fontSize=8,
            leading=11,
            textColor=MUTED,
            backColor=colors.HexColor("#f8fafc"),
            borderPadding=8,
        ),
    }

    lat = analysis.inputs.latitude
    lng = analysis.inputs.longitude
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    m = analysis.metrics

    story: list[Any] = [
        Paragraph("CHITTA Site Assessment Report", styles["Title"]),
        Paragraph(
            "Climate Heuristics &amp; Intelligent Turbine Terrain Analysis",
            styles["Subtitle"],
        ),
        Spacer(1, 6),
        Paragraph(f"<b>Coordinates:</b> {lat:.5f}, {lng:.5f}", styles["Body"]),
        Paragraph(f"<b>Generated:</b> {_esc(ts)}", styles["Body"]),
        Spacer(1, 12),
        Paragraph(
            f"<b>Total suitability:</b> {_fmt_score(analysis.totalSuitabilityScore)}/100",
            styles["Body"],
        ),
        Spacer(1, 16),
    ]

    story += _section_heading("Executive Summary", styles)
    # If agent analysis present, prepend coordinator decision label
    if analysis.agentAnalysis:
        coord = analysis.agentAnalysis.coordinator
        dec_label = coord.finalDecision.upper()
        story.append(
            Paragraph(
                f"<b>Coordinator assessment: {_esc(dec_label)}</b>",
                ParagraphStyle(
                    "DecisionBadge",
                    parent=styles["Body"],
                    fontSize=10,
                    textColor=ACCENT,
                    spaceAfter=4,
                ),
            )
        )
    story.append(Paragraph(_esc(analysis.report.executiveSummary), styles["Body"]))
    story.append(Spacer(1, 8))

    story += _section_heading("Score Summary", styles)
    score_rows: list[list[str]] = [["Metric", "Score", "Notes"]]
    score_rows += [
        ["Wind", _fmt_score(m.windScore), f"Hub height: {m.windSpeedAtHub:.1f} m/s" if m.windSpeedAtHub else "Regional wind potential"],
        ["Terrain", _fmt_score(m.terrainScore), f"Slope: {m.slopePct:.1f}%" if m.slopePct else "Buildability & roughness"],
        ["Infrastructure", _fmt_score(m.infrastructureScore), "Road & grid access (OSM)"],
        ["Environmental", _fmt_score(m.environmentalScore), f"Land cover: {m.landCoverClass or 'unknown'}"],
        ["Population", _fmt_score(m.populationScore), f"{m.settlementCount15km or 0} settlements (15 km)"],
        ["Confidence", f"{m.confidenceScore:.0f}", "Data source completeness"],
        ["Total suitability", _fmt_score(analysis.totalSuitabilityScore), "Weighted composite (v2.0.0)"],
    ]
    story.append(_score_table(score_rows))
    story.append(Spacer(1, 8))

    if heatmap and heatmap.bestCells:
        story += _section_heading("Top 3 Candidate Zones", styles)
        zone_rows = [["Rank", "Label", "Total", "Wind", "Terrain", "Coords"]]
        for idx, cell in enumerate(heatmap.bestCells[:3], start=1):
            cm = cell.metrics
            zone_rows.append(
                [
                    str(idx),
                    cell.label,
                    _fmt_score(cm.totalSuitability),
                    _fmt_score(cm.windScore),
                    _fmt_score(cm.terrainScore),
                    f"{cell.latitude:.4f}, {cell.longitude:.4f}",
                ]
            )
        zone_table = Table(
            zone_rows,
            colWidths=[0.45 * inch, 1.5 * inch, 0.65 * inch, 0.65 * inch, 0.75 * inch, 1.5 * inch],
        )
        zone_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(zone_table)
        story.append(
            Paragraph(
                f"Heatmap coverage: {heatmap.radiusKm:.0f} km radius, {heatmap.gridSize}×{heatmap.gridSize} grid.",
                styles["Subtitle"],
            )
        )

    # Agent analysis section
    if analysis.agentAnalysis:
        coord = analysis.agentAnalysis.coordinator
        story += _section_heading("Agent Analysis", styles)
        if coord.topStrengths:
            story.append(Paragraph("<b>Key strengths:</b>", styles["Body"]))
            story += _bullet_list(coord.topStrengths, styles["Body"])
        if coord.topRisks:
            story.append(Paragraph("<b>Key risks:</b>", styles["Body"]))
            story += _bullet_list(coord.topRisks, styles["Body"])
        if coord.contradictionNotes:
            story.append(Paragraph("<b>Contradictions:</b>", styles["Body"]))
            story += _bullet_list(coord.contradictionNotes, styles["Body"])
        story.append(Spacer(1, 4))
        story.append(Paragraph("<b>Per-agent summaries:</b>", styles["Body"]))
        for agent in analysis.agentAnalysis.agents:
            story.append(
                Paragraph(
                    f"<b>{_esc(agent.agentName)}</b> [{_esc(agent.status)}]: {_esc(agent.summary)}",
                    styles["Body"],
                )
            )
            story.append(Spacer(1, 3))
        story.append(Spacer(1, 6))

    # Economic Feasibility section
    if analysis.economicMetrics:
        em = analysis.economicMetrics
        a = em.assumptions
        story += _section_heading("Economic Feasibility (Preliminary)", styles)
        eco_rows = [
            ["Metric", "Value", "Notes"],
            ["Capacity factor", f"{em.capacityFactor:.1%}", "Estimated from hub-height wind speed"],
            ["Annual energy (AEP)", f"{em.annualEnergyMwh:,.0f} MWh/yr", f"{a.turbineCount} × {a.turbineRatingMw}MW turbines"],
            ["CAPEX estimate", f"${em.capexUsd / 1e6:.1f}M", f"${a.capexUsdPerMw / 1e6:.2f}M/MW baseline"],
            ["OPEX/year", f"${em.opexUsdPerYear / 1e3:.0f}k", f"{a.opexPctOfCapex * 100:.0f}% of CAPEX"],
            ["Annual revenue", f"${em.annualRevenueUsd / 1e6:.2f}M", f"@ ${a.electricityPriceUsdPerMwh}/MWh"],
            ["Simple payback", f"{em.paybackYears:.1f} yr" if em.paybackYears else "N/A", "Before financing costs"],
            ["LCOE", f"${em.lcoeUsdPerMwh:.1f}/MWh", f"{a.discountRate*100:.0f}% discount, {a.projectLifeYears}yr life"],
        ]
        story.append(_score_table(eco_rows))
        story.append(Spacer(1, 6))
        story += _bullet_list(em.limitations[:4], styles["Disclaimer"])
        story.append(Spacer(1, 8))

    story += _development_risk_section(analysis, styles)

    story += _section_heading("Wind Findings", styles)
    story += _bullet_list(_wind_findings(analysis), styles["Body"])

    story += _section_heading("Terrain Findings", styles)
    story += _bullet_list(_terrain_findings(analysis), styles["Body"])

    story += _section_heading("Risks and Limitations", styles)
    limitations = list(analysis.report.risks) + list(analysis.report.confidenceNotes)
    story += _bullet_list(limitations, styles["Body"])

    story += _section_heading("Recommendations", styles)
    story += _bullet_list(analysis.report.recommendations, styles["Body"])

    story += _section_heading("Data Sources", styles)
    story += _bullet_list(analysis.report.dataSources, styles["Body"])


    story += _section_heading("Methodology & Audit Trail", styles)
    meth = analysis.methodology
    story.append(Paragraph(f"<b>Analysis ID:</b> {_esc(analysis.analysisId)}", styles["Body"]))
    story.append(Paragraph(f"<b>Generated:</b> {_esc(meth.generatedAt)}", styles["Body"]))
    story.append(Spacer(1, 6))
    meta_rows = [
        ["Field", "Value"],
        ["Wind data source", meth.windDataSource],
        ["Wind date range", meth.windDateRange],
        ["Elevation source", meth.elevationSource],
        ["Formula version", meth.scoringFormulaVersion],
        ["Terrain method", meth.terrainRoughnessMethod],
        ["Confidence method", meth.confidenceCalculationMethod],
        ["Fallback status", meth.fallbackStatus],
    ]
    meta_table = Table(meta_rows, colWidths=[1.6 * inch, 4.9 * inch])
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>Wind score formula:</b> {_esc(WIND_SCORE_FORMULA_PLAIN)}", styles["Body"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<b>Total suitability formula:</b> {_esc(TOTAL_SUITABILITY_FORMULA_PLAIN)}", styles["Body"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("<b>Audit trail</b>", styles["Body"]))
    story += _bullet_list(analysis.auditTrail, styles["Body"])
    if heatmap and heatmap.auditTrail:
        story.append(Paragraph("<b>Heatmap audit trail</b>", styles["Body"]))
        story += _bullet_list(heatmap.auditTrail, styles["Body"])


    story += _section_heading("Disclaimer", styles)
    story.append(Paragraph(_esc(DISCLAIMER), styles["Disclaimer"]))

    doc.build(story)
    return buffer.getvalue()
