"""
AI synthesis service for CHITTA.

Orchestrates evidence building, LLM generation, citation validation,
and fallback to deterministic synthesis.
"""
from __future__ import annotations
import uuid
from datetime import datetime, timezone

from app.api.schemas import (
    ProspectingResponse,
    SimulationResponse,
    SiteAnalysisResponse,
)
from app.llm import get_provider
from app.synthesis.evidence import build_evidence_packets
from app.synthesis.prompts import OUTPUT_SCHEMA, build_system_prompt


async def synthesize(
    mode: str,
    site_analysis: SiteAnalysisResponse | None = None,
    prospecting: ProspectingResponse | None = None,
    simulation: SimulationResponse | None = None,
) -> dict:
    provider = get_provider()

    evidence_packets = build_evidence_packets(mode, site_analysis, prospecting, simulation)
    ev_dict_list = [e.to_dict() for e in evidence_packets]
    ev_id_set = {e.evidenceId for e in evidence_packets}

    system_prompt = build_system_prompt(mode, ev_id_set)
    user_payload = {"mode": mode, "evidence": ev_dict_list}

    validation_warnings: list[str] = []
    narrative: dict | None = None

    try:
        raw = await provider.generate_json(system_prompt, user_payload, OUTPUT_SCHEMA)
        narrative, warnings = _validate(raw, ev_id_set)
        validation_warnings.extend(warnings)
    except Exception as exc:
        validation_warnings.append(f"LLM call failed: {exc!s} — returning deterministic fallback.")
        narrative = None

    if narrative is None:
        from app.llm.mock_provider import MockProvider
        fallback = MockProvider()
        narrative = await fallback.generate_json(system_prompt, user_payload, OUTPUT_SCHEMA)
        validation_warnings.append("Narrative generated by deterministic fallback (not LLM).")

    import os
    return {
        "synthesisId": str(uuid.uuid4()),
        "mode": mode,
        "provider": os.environ.get("CHITTA_LLM_PROVIDER", "mock"),
        "model": provider.model,
        "narrative": narrative,
        "evidencePackets": ev_dict_list,
        "validationWarnings": validation_warnings,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
    }


def _validate(raw: dict, ev_id_set: set[str]) -> tuple[dict | None, list[str]]:
    warnings: list[str] = []
    required = [
        "executiveSummary", "strategicAssessment", "strongestSignals",
        "majorRisks", "economicNarrative", "infrastructureNarrative",
        "environmentalNarrative", "recommendations", "warnings",
        "citations", "generatedFromEvidenceIds",
    ]
    for field in required:
        if field not in raw:
            warnings.append(f"LLM response missing required field: {field}")
            return None, warnings

    bad_eids: list[str] = []
    for citation in raw.get("citations", []):
        for eid in citation.get("evidenceIds", []):
            if eid not in ev_id_set:
                bad_eids.append(eid)

    if bad_eids:
        warnings.append(
            f"Citation validation failed — {len(bad_eids)} unknown evidenceId(s): "
            f"{', '.join(bad_eids[:5])}. Falling back to deterministic synthesis."
        )
        return None, warnings

    return raw, warnings
